# Generated by Django 6.0.3 on 2026-03-16 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Esempi: "Primi Piatti", "Secondi", "Bevande", "Dolci"', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredienti', models.TextField(help_text='Lista degli ingredienti separati da virgola')),
                ('allergeni', models.BooleanField(default=False, help_text='Selezionare se il piatto contiene allergeni')),
                ('attivo', models.BooleanField(default=True, help_text='Il piatto è attualmente nel menu')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
                'db_table': 'piatti',
            },
        ),
    ]
