# Generated by Django 6.0.3 on 2026-03-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_categoria_options_alter_piatto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='disponibile',
            field=models.BooleanField(default=True, help_text='Il piatto è visibile ma non ordinabile se False'),
        ),
    ]
