# Generated by Django 6.0.3 on 2026-03-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_piatto_disponibile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='piatto',
            options={'verbose_name': 'Piatto', 'verbose_name_plural': 'Piatti'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Esempi: "Primi Piatti", "Secondi", "Bevande", "Dolci"', max_length=100, unique=True, verbose_name='Nome Categoria'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='allergeni',
            field=models.BooleanField(default=False, help_text='Selezionare se il piatto contiene sostanze allergizzanti', verbose_name='Contiene Allergeni'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='attivo',
            field=models.BooleanField(default=True, help_text='Indica se il piatto è presente nel menu corrente', verbose_name='Piatto Attivo'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='menu.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='disponibile',
            field=models.BooleanField(default=True, help_text="Se disattivato, il piatto apparirà come 'esaurito' e non sarà ordinabile", verbose_name='Disponibilità'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='ingredienti',
            field=models.TextField(help_text='Lista degli ingredienti separati da virgola', verbose_name='Ingredienti'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome del Piatto'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prezzo (€)'),
        ),
    ]
