# Generated by Django 6.0.3 on 2026-03-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_categoria_options_alter_piatto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='piatto',
            options={'verbose_name': 'Piatto'},
        ),
    ]
