# Generated by Django 6.0.3 on 2026-03-16 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_categoria_options_alter_piatto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='piatto',
            options={},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Esempi: "Primi Piatti", "Secondi", "Bevande", "Dolci"', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='allergeni',
            field=models.BooleanField(default=False, help_text='Selezionare se il piatto contiene sostanze allergizzanti'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='attivo',
            field=models.BooleanField(default=True, help_text='Indica se il piatto è presente nel menu corrente'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='menu.categoria'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='disponibile',
            field=models.BooleanField(default=True, help_text="Se disattivato, il piatto apparirà come 'esaurito' e non sarà ordinabile"),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='ingredienti',
            field=models.TextField(help_text='Lista degli ingredienti separati da virgola'),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
